### PR TITLE
Fixed bugs in Main.py and requirement.txt

### PR DESCRIPTION
**Pull request by ChaoticBlack**
1. The requirements on line 8, 15 and 20 were unnecessary and out dated. They were throwing errors. 
2. There was a parenthesis error on line 70 and 173 of Main.py.

Resolved both these issues in this pull request.

### CODE REVIEW

**Comment by ChaoticBlack** [comment]
I hope this is correct!

**Comment by ChaoticBlack** [comment]
I've run all the tests, it now runs perfectly without any errors

**Comment by annu12340** [comment]
Pls resolve the conflicts

**Comment by ChaoticBlack** [comment]
Done!

**Comment by annu12340** [comment]
Thanks for the pr 😄

**Pull request merged**
