### PR TITLE
Improved readme, added tech stack and installation guide

### PR DESCRIPTION
**Pull request by ChaoticBlack**
I've written an easy to understand and follow readme. Hope it is merged!

### CODE REVIEW

**Comment by annu12340** [comment]
Everything looks good 👍 

One small change is required 
Screenshot
Add the installation steps in separate lines

**Comment by ChaoticBlack** [comment]
Ok! On it!

**Comment by ChaoticBlack** [comment]
Please check now!

**Comment by annu12340** [comment]
Thanks for the pr 😄

**Pull request merged**
